// Pulls totals + top photo events from GoatCounter and writes data/stats.json.
// Skipped (gracefully) if GOATCOUNTER_TOKEN env var is not set.
//
// Get a token at https://toddejhill.goatcounter.com/user/api
//
// Usage:
//   GOATCOUNTER_TOKEN=xxx npm run build         (bash / WSL / Git Bash)
//   $env:GOATCOUNTER_TOKEN="xxx"; npm run build (PowerShell)
//   set GOATCOUNTER_TOKEN=xxx&& npm run build   (cmd)

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const STATS_FILE = path.join(ROOT, "data", "stats.json");

const SITECODE = process.env.GOATCOUNTER_SITE || "toddejhill";
const TOKEN = process.env.GOATCOUNTER_TOKEN;
const TOP_N = 6;
const START = "2020-01-01T00:00:00Z"; // effectively "all time" (ISO 8601 required by API)

if (!TOKEN) {
  console.log("[stats] GOATCOUNTER_TOKEN not set — skipping (data/stats.json untouched).");
  console.log(`[stats] Get a token at https://${SITECODE}.goatcounter.com/user/api`);
  process.exit(0);
}

const API = `https://${SITECODE}.goatcounter.com/api/v0`;
const headers = { Authorization: `Bearer ${TOKEN}`, Accept: "application/json" };

async function get(suffix) {
  const url = `${API}${suffix}`;
  const res = await fetch(url, { headers });
  if (!res.ok) {
    throw new Error(`GoatCounter API ${res.status} on ${suffix}: ${await res.text()}`);
  }
  return res.json();
}

async function main() {
  const end = new Date().toISOString();

  // Sanity check the token first so the error is obvious if it's wrong.
  await get("/me");

  const totals = await get(`/stats/total?start=${START}&end=${end}`);
  // Shape (per OpenAPI): { total, total_events, total_utc, stats: [...] }

  const hits = await get(`/stats/hits?start=${START}&end=${end}&limit=100`);
  // Shape: { hits: [{ path, event, count, ... }], total, more }

  const photoHits = (hits.hits || [])
    .filter(h => h.event && h.path && h.path.startsWith("/photo/"))
    .sort((a, b) => (b.count || 0) - (a.count || 0))
    .slice(0, TOP_N)
    .map(h => ({
      src: "images/" + h.path.replace(/^\/photo\//, ""),
      views: h.count || 0,
    }));

  const stats = {
    comment: "Auto-generated by scripts/build-stats.js from GoatCounter API. Do not edit by hand.",
    updatedAt: new Date().toISOString(),
    totalVisitors: totals.total || 0,
    totalPhotoViews: photoHits.reduce((sum, h) => sum + h.views, 0),
    topPhotos: photoHits,
  };

  await writeFile(STATS_FILE, JSON.stringify(stats, null, 2) + "\n");
  console.log(`[stats] Wrote ${path.relative(ROOT, STATS_FILE)}: ${stats.totalVisitors} unique visitors, ${stats.topPhotos.length} top photos.`);
}

main().catch(err => {
  console.error(`[stats] ${err.message}`);
  // Don't fail the whole build — just leave stats.json as-is.
  process.exit(0);
});
